name: resolve-package-dependencies

on:
  pull_request:
    paths:
      - "Features/Package.swift"

env:
  DEVELOPER_DIR: /Applications/Xcode_26.0.app/Contents/Developer

jobs:
  resolve-package-deps:
    runs-on: macos-15
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - name: Resolve package dependencies
        run: xcodebuild -resolvePackageDependencies
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Resolve package dependencies
