name: resolve-package-dependencies

on:
  pull_request:
    paths:
      - "Features/Package.swift"

jobs:
  resolve-package-deps:
    runs-on: macos-15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.4.app
      - name: Resolve package dependencies
        run: xcodebuild -resolvePackageDependencies
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Resolve package dependencies
