name: resolve-package-dependencies

on:
  pull_request:
    paths:
      - "Features/Package.swift"

env:
  DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer

jobs:
  resolve-package-deps:
    runs-on: macos-15
    permissions:
      contents: write
      workflows: write
    steps:
      - uses: actions/checkout@v5
      - name: Pull Remote Changes
        run: xcodebuild -resolvePackageDependencies
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Resolve package dependencies
