name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Run tests
        run: |
          xcodebuild \
            -project NASAClient.xcodeproj \
            -scheme NASAClient \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            -skipMacroValidation \
            test
